server:
  port: 8082

spring:
  application:
    name: client-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: true
    config:
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

service-book:
  url: http://localhost:8081

book-service:
  url: http://localhost:8081
  ribbon:
    eureka:
     enabled: true
    ServerListRefreshInterval: 1000


#
#book-service:
#  ribbon:
#    listOfServers: localhost:8082,localhost:8092
#    eureka:
#      enabled: true


