server:
  port: 8082

spring:
  application:
    name: client-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

service-book:
  url: http://localhost:8081


